development:
  adapter: postgresql
  encoding: unicode
  database: raffler_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: raffler_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: raffler_production
  pool: 5
  username:
  password:
